name: CI

on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  testsuite:
    name: Unittest
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql/mysql-server:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -uroot -ppassword" --health-interval=10s --health-timeout=5s --health-retries=10

    steps:
      - uses: actions/checkout@v4
      #これだとマイグレーションで失敗する
      - uses: ./.github/actions/setup-php


      # - uses: shivammathur/setup-php@2
      #   with:
      #     php-version: '8.2'
      # - name: Install Dependencies
      #   run: |
      #     curl -sS https://getcomposer.org/installer | php -- --version=2.7.6
      #     sudo mv composer.phar /usr/local/bin/composer
      #     composer install --no-interaction --prefer-dist

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: Generate key
        run: php artisan key:generate

      - name: Set Up Database
        run: |
          php artisan migrate

      - name: Execute tests
        run: |
          php artisan test

  # coding-standard:
  #   name: Pint
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: ./.github/actions/setup-php

  #     - name: Execute pint
  #       run: vendor/bin/pint -v --test
  # static-analysis:
  #   name: Larastan
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: ./.github/actions/setup-php

  #     - name: Run larastan
  #       run: vendor/bin/phpstan analyse --memory-limit=-1
  # react-ci:
  #   name: react-ci
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: npm install
  #       run: npm i

  #     - name: Run format and lint
  #       run: npm run ci
