name: CI

on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  testsuite:
    name: Unittest
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql/mysql-server:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping -uroot -ppassword" --health-interval=10s --health-timeout=5s --health-retries=10
    env:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: testing
      DB_USERNAME: sail
      DB_PASSWORD: password

    steps:
      - uses: actions/checkout@v4
      #これだとマイグレーションで失敗する
      # - uses: ./.github/actions/setup-php

      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - name: Install Dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php -- --version=2.7.6
          sudo mv composer.phar /usr/local/bin/composer
          composer install --no-interaction --prefer-dist
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: start mysql
        run: ./vendor/bin/sail up -d mysql

      - name: Start Sail
        run: |
          ./vendor/bin/sail up -d

      - name: Set Up Database
        run: |
          ./vendor/bin/sail artisan migrate --seed

      - name: Delete old node_modules and package-lock.json
        run: |
          rm -rf package-lock.json

      - name: npm install
        run: |
          npm install

      - name: Build assets
        run: |
          npm run build

      - name: Execute tests
        run: |
          ./vendor/bin/sail test

  # coding-standard:
  #   name: Pint
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: ./.github/actions/setup-php

  #     - name: Execute pint
  #       run: vendor/bin/pint -v --test
  # static-analysis:
  #   name: Larastan
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: ./.github/actions/setup-php

  #     - name: Run larastan
  #       run: vendor/bin/phpstan analyse --memory-limit=-1
  # react-ci:
  #   name: react-ci
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: npm install
  #       run: npm i

  #     - name: Run format and lint
  #       run: npm run ci
