name: CI

on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  testsuite:
    name: Unittest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./clone-todo-for-ci
    steps:
      - uses: actions/checkout@v4

      - name: cp env
        run: cp .env.ci .env

      - name: composer install
        run: docker run --rm -u "$(id -u):$(id -g)" -v $(pwd):/var/www/html -w /var/www/html laravelsail/php81-composer:latest composer install --ignore-platform-reqs

      # 先に起動しておく
      - name: start mysql
        run: ./vendor/bin/sail up -d mysql

      - name: start
        run: ./vendor/bin/sail up -d

      - name: generate key
        run: ./vendor/bin/sail artisan key:generate

      - name: migrate
        run: ./vendor/bin/sail artisan migrate

      - name: test
        run: ./vendor/bin/sail test

  # coding-standard:
  #   name: Pint
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: ./.github/actions/setup-php

  #     - name: Execute pint
  #       run: vendor/bin/pint -v --test
  # static-analysis:
  #   name: Larastan
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: ./.github/actions/setup-php

  #     - name: Run larastan
  #       run: vendor/bin/phpstan analyse --memory-limit=-1
  # react-ci:
  #   name: react-ci
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: npm install
  #       run: npm i

  #     - name: Run format and lint
  #       run: npm run ci
